OPENAI_API_KEY = "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"

[connections.snowflake]
account = "QFCXXYY-UI14740"
user = "YAGHWINDER"
role = "ACCOUNTADMIN"
warehouse = "COMPUTE_WH"
database = "YPO"
schema = "YPO_DATA"
password="Snowflake@1234"